apiVersion: skaffold/v2beta11
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
metadata:
  name: big-tix
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: big-tix-dev
  artifacts:
  - image: us.gcr.io/big-tix-dev/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '/src/**/*.ts'
          dest: .
